# Generated by Django 4.0.5 on 2022-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_subgroup_customuser_group_customuser_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, default='-', max_length=150),
        ),
    ]
