# Generated by Django 4.0.5 on 2022-07-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textobject',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='chapter',
        ),
        migrations.AddField(
            model_name='textobject',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
        migrations.AddField(
            model_name='textobject',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
