# Generated by Django 4.0.5 on 2022-07-16 07:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_coursecategory_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='presentation',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
