# Generated by Django 4.0.5 on 2022-07-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_course_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='textobject',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.chapter'),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.chapter'),
        ),
    ]
