# Generated by Django 4.0.5 on 2022-07-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_textobject_chapter_videoobject_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='textobject',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
