# Generated by Django 4.0.5 on 2022-07-16 09:49

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_chapter_duration_textobject_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('duration', models.DurationField(null=True)),
                ('url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='position',
        ),
        migrations.DeleteModel(
            name='TextObject',
        ),
        migrations.DeleteModel(
            name='VideoObject',
        ),
        migrations.AddField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.chapter'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
    ]
