# Generated by Django 4.0.5 on 2022-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_lecture_remove_videoobject_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
