# Generated by Django 4.0.5 on 2022-07-16 09:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_chapter_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
