# Generated by Django 4.0.5 on 2022-07-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_lecture_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.AddField(
            model_name='chapter',
            name='lectures',
            field=models.ManyToManyField(related_name='lectures', to='learning.lecture'),
        ),
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.ManyToManyField(related_name='chapters', to='learning.chapter'),
        ),
    ]
