# Generated by Django 4.0.5 on 2022-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_rename_course_permissions_coursepermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepermissions',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coursepermissions',
            name='start_date',
            field=models.DateField(),
        ),
    ]
