# Generated by Django 4.0.5 on 2022-07-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
    ]
