# Generated by Django 4.0.5 on 2022-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_card_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='url',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
