# Generated by Django 4.0.5 on 2022-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_lecturetype_lecture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
