# Generated by Django 4.0.5 on 2022-07-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_lecture_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='type',
            new_name='lecture_type',
        ),
    ]
