# Generated by Django 4.0.5 on 2022-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_rename_type_lecture_lecture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='zip_file',
            field=models.FileField(blank=True, upload_to='archives/'),
        ),
    ]
