# Generated by Django 4.0.5 on 2022-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_alter_question_test_alter_testinstance_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
