# Generated by Django 4.0.5 on 2022-07-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_test_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',), 'verbose_name_plural': 'Întrebări'},
        ),
    ]
